### ISSUE TITLE
Problem: API compatibility broken between 4.1.0 and 4.1.1+

### ISSUE THREAD

**Issue by bluca** [zeromq/zeromq4-1#114]
Due to commit https://github.com/zeromq/zeromq4-1/pull/6/commits/ed6bf9f1781d082d198b098e06b906762f38f15e merged via PR https://github.com/zeromq/zeromq4-1/pull/6 which was part of the 4.1.1 release, the behaviour of the socket bind/unbind API has changed when IPv6 is enabled.

Before that commit, you could bind "tcp://127.0.0.1:1234" and unbind using the same string, and it would work. After that commit, it no longer works and zmq_unbind returns an error.

This is because the unbind now needs to happen with the actual endpoint string, which when IPv6 is enable would be:
"tcp://[::ffff:127.0.0.1]:1234"

Given there have been many releases since 4.1.1, I'd say it's probably too late now to change back. But maybe we could add a note to the NEWS file so that users can expect this and avoid spending time debugging?

I found out about this issue when staging the upgrade of libzmq from 4.0.4 to 4.1.5 in our build system - and tests started blowing up left and right.

To reproduce:

```
#include <assert.h>
#include <zmq.h>

int main (int argc, char **argv)
{
    void *ctx = zmq_ctx_new ();
    assert (ctx);

    void *sb = zmq_socket (ctx, ZMQ_REP);
    assert (sb);

    int ipv6 = 1;
    int rc = zmq_setsockopt (sb, ZMQ_IPV6, &ipv6, sizeof (int));
    assert (rc == 0);

    rc = zmq_bind (sb, "tcp://127.0.0.1:9999");
    assert (rc == 0);

    rc = zmq_unbind (sb, "tcp://127.0.0.1:9999");
    assert (rc == 0);

    rc = zmq_close (sb);
    assert (rc == 0);

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);
}
```

And I found the culprit by bisecting (save the above code as api_test.cpp and the following script as bisect.sh):

```
#!/bin/bash
make clean
make -j5
gcc -I./include -L./.libs -lzmq api_test.cpp
LD_LIBRARY_PATH=./.libs ./a.out
if [ $? -gt 0 ]
then
  exit 1
else
  exit 0
fi
```

```
git bisect start HEAD v4.1.0
git bisect run ./bisect.sh

...

ed6bf9f1781d082d198b098e06b906762f38f15e is the first bad commit
commit ed6bf9f1781d082d198b098e06b906762f38f15e
Author: lysyloren <lysy_loren@gmail.com>
Date:   Wed Oct 29 10:17:30 2014 +0100

    Unbind socket with real endpoint when binding by wild-card * address

:040000 040000 bd07179b7b473a130dd8d95b9f1752093beecb2f b16abb01cf07f6908b9111b7b65236cd0b1abe90 M	doc
:040000 040000 e984021e4aff2332f4ea9b73a84fb178323fdb44 bde4cd826792171494d46a70e7f14faeb39b340e M	src
:040000 040000 2751e15d2321ce21f600d59695e349529c39fd2b 95b186d4b1ffce3202a7fb7c6233411201c847c8 M	tests
bisect run success
```

**Comment by hintjens** [comment]
Good catch. This is unfortunate but it's what happens when there are gaps in the test cases (and the IPv6 API isn't fully tested yet.)

TBH I think the current behavior is a bug. The semantics of bind/unbind are that they accept the same strings. If we introduced a bug then we can fix it.

**Comment by bluca** [comment]
I agree. From what I can gather the original fix was for the case where the wildcard bind is done, which is fair enough. But when a full endpoint is passed it should just work.
