### ISSUE TITLE
Smalltalk?

### ISSUE THREAD

**Issue by davelab6** [zeromq/zeromq4-1#120]
@hintjens this is probably the wrong place to ask this, but, hi :) 

To what extent has Smalltalk influenced your work, and specifically your work on zemomq?

**Comment by hintjens** [comment]
I've never used Smalltalk so I've no idea really. My background has always
been pragmatic business applications, so the first five years of my career
was Cobol.

**Comment by davelab6** [comment]
Interesting! See, Alan Kay said that he made a mistake naming his vision "object orientation" because (in gestalt terms) it focuses on the figure, and takes attention away from the ground - which is messages! That's why I thought you might have a connection there. No matter :) Thanks!
