### ISSUE TITLE
Problem: ZeroMQ 4.1 downloads coming from VM that is about to be shut down

### ISSUE THREAD

**Issue by ewen-naos-nz** [zeromq/zeromq4-1#123]
The [downloads for ZeroMQ 4.1](http://zeromq.org/intro:get-the-software) are coming from `download.zeromq.org` which is a CNAME to an iMatix VM.  That VM is about to be shut down (somewhere between late May and mid-June).  When that VM is shut down the downloads for ZeroMQ 4.1 will not work if they are not changed.

Suggested solution:

0.   Tag at least the most recent (4.1.4) release in the GitHub repository to create a GitHub release at the commit representing 4.1.4.

0.   Arrange for the auto-builder to run on `zeromq4-1` and upload ready-to-build archives (and/or manually upload the existing archives)

0.   Update [the download page](http://zeromq.org/intro:get-the-software) to link to the GitHub release hosted archives.

Ewen

**Comment by ewen-naos-nz** [comment]
Looks like there is a [v4.1.4](https://github.com/zeromq/zeromq4-1/releases/tag/v4.1.4) tag already, so in theory it just needs someone with commit access to the `zeromq/zeromq4-1` repository to upload the existing archives (linked from [downloads for ZeroMQ 4.1](http://zeromq.org/intro:get-the-software)), and update the download links.

Ewen

**Comment by ewen-naos-nz** [comment]
Please update the ZeroMQ 3.2 download links to point at:

https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.zip

and the ZeroMQ 4.1 download links to point at:

https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.tar.gz
https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.zip

and the "previous releases" links to point at:

[Earlier 3.x releases](https://zeromq.github.io/zeromq3-x/)
[Earlier 4.x releases](https://zeromq.github.io/zeromq4-1/)

Plus a note that even older releases have been archived on archive.org, eg at:

https://archive.org/search.php?query=subject%3A%22zeromq%22%20subject%3A%22message_queue%22

(Unfortunately there isn't yet a ZeroMQ Collection; I'll ask again tomorrow if I haven't heard back.)

Ewen

**Comment by hintjens** [comment]
Done, thanks.

**Comment by bluca** [comment]
@ewen-naos-nz @hintjens - want me to add the old tarballs to the respective tag/release here on Github?

**Comment by ewen-naos-nz** [comment]
@bluca: If you'd be willing to "make GitHub releases" with the old tarballs attached for each of the ZeroMQ 4.1 `v4.1.x` tags, and have access to do so, that'd be awesome.  [My post on the `zeromq-dev` list](http://lists.zeromq.org/pipermail/zeromq-dev/2016-May/030538.html) explains the actual process when the `v4.1.x` tag already exists (it was very confusing to figure out).

The original zip files can be found via links at:

https://imatix-legacy.github.io/zeromq-archived/

or at the moment via links at (turned on again):

http://download.zeromq.org/

Please double check the [MD5SUMS](http://download.zeromq.org/MD5SUMS) and [SHA1SUMS](http://download.zeromq.org/SHA1SUMS) of the files you download before attaching them to make sure they're complete/unchanged.

Thanks,

Ewen

**Comment by bluca** [comment]
Sure will take care of it, thanks for the pointers

**Comment by bluca** [comment]
All done, checksums match.
@hintjens @ewen-naos-nz - shall I upload to the zeromq4-x repo too?

**Comment by ewen-naos-nz** [comment]
@bluca: Thanks!  If you have time to upload the matching files for the zeromq4-x tags as well, that'd be great.  And if you're extra enthusiastic, it might be worth doing a few more of the zeromq3-x ones as well (I know some distros are still shipping it as an option).  I suspect it's not worth going any further back than that (even though I know there are still a few distros shipping ZeroMQ 2.x as a backwards compatibility option, but presumably that'll never change so they can probably just stick with their existing build).

Ewen

**Comment by bluca** [comment]
I went ahead and added all of them :-)
4-1, 4-x, 3-x, 2-x, 2-0 and CZMQ. For each of the releases I uploaded the tar.gz, zip, MD5SUMS and SHA1SUMS of the archive of each release.

**Comment by ewen-naos-nz** [comment]
@bluca: Wow, that's awesome!  Thanks so much for doing that.  It's great that gives a second copy of most of the original release archives (other than archive.org) that will stay online once the iMatix VM gets shut down (later this month).

Ewen
