### ISSUE TITLE
Unable to build universal framework for iOS

### ISSUE THREAD

**Issue by Jeyamahesan** [zeromq/zeromq4-1#130]
Using zeromq v4.0.8 building a universal framework is a success.But unable to build a universal framework for zeromq v4.1.5..While compiling the framework, its showing lot of errors.Using the script (https://github.com/drewcrawford/libzmq-ios) also unable to build the library it is showing the error as "make: *** No targets specified and no makefile found.  Stop."

**Comment by bluca** [comment]
Does it work from libzmq master? If not, would you please send a PR to fix it?

**Comment by Jeyamahesan** [comment]
@bluca Yes!!! it's working in libzmq master. Thank you very much. What is the reason for not working on zeromq v4.1.5?

**Comment by bluca** [comment]
I don't really know, I'm not familiar with that IOS framework. If you find the commit(s) that fixed it and want to backport it here we'll merge it.
