### ISSUE TITLE
compilation error in VS2010 

### ISSUE THREAD

**Issue by alpo** [zeromq/zeromq4-1#152]
Steps to reproduce:
1) clone repo (latest commit was ff8b0aa6eca447452a173a161aa9d873965edcac)
2) use vs2010 and open builds\msvc\vs2010\libzmq.sln
3) try to build without any changes

`
1>..\..\..\..\src\socket_base.cpp(1300): error C2511: 'void zmq::socket_base_t::event_connected(const std::string &,zmq::fd_t)' : overloaded member function not found in 'zmq::socket_base_t'
1>          c:\zeromq4-1\src\socket_base.hpp(61) : see declaration of 'zmq::socket_base_t'
1>..\..\..\..\src\socket_base.cpp(1315): error C2511: 'void zmq::socket_base_t::event_listening(const std::string &,zmq::fd_t)' : overloaded member function not found in 'zmq::socket_base_t'
1>          c:\zeromq4-1\src\socket_base.hpp(61) : see declaration of 'zmq::socket_base_t'
1>..\..\..\..\src\socket_base.cpp(1325): error C2511: 'void zmq::socket_base_t::event_accepted(const std::string &,zmq::fd_t)' : overloaded member function not found in 'zmq::socket_base_t'
1>          c:\zeromq4-1\src\socket_base.hpp(61) : see declaration of 'zmq::socket_base_t'
1>..\..\..\..\src\socket_base.cpp(1335): error C2511: 'void zmq::socket_base_t::event_closed(const std::string &,zmq::fd_t)' : overloaded member function not found in 'zmq::socket_base_t'
1>          c:\zeromq4-1\src\socket_base.hpp(61) : see declaration of 'zmq::socket_base_t'
1>..\..\..\..\src\socket_base.cpp(1345): error C2511: 'void zmq::socket_base_t::event_disconnected(const std::string &,zmq::fd_t)' : overloaded member function not found in 'zmq::socket_base_t'
1>          c:\zeromq4-1\src\socket_base.hpp(61) : see declaration of 'zmq::socket_base_t'
`

**Comment by mattbolgercsiro** [comment]
Just hit the same issue. Looks like the signature was changed in the cpp but not the hpp (compared to the last stable source zip on http://zeromq.org/intro:get-the-software. 

zmq::fd_t isn't just an int under Windows.

Unfortunately the latest stable source download from http://zeromq.org/intro:get-the-software is also broken on Windows as it's missing the version.rc.in

**Comment by bluca** [comment]
Likely due to https://github.com/zeromq/zeromq4-1/pull/149 @jens-auer could you please have a look?

I'll fix the version.rc.in during the weekend if someone else doesn't beat me to it

**Comment by jens-auer** [comment]
@bluca I've fixed the wrong prototypes

**Comment by bluca** [comment]
Thanks @jens-auer for the quick turnaround. Compilation should be fixed now @alpo @mattbolgercsiro 

I noticed I had already fixed the version.rc.in problem last month via https://github.com/zeromq/zeromq4-1/commit/e00b2c4b082cf74628e26f719ebb98bc8e5b553f

So I'll close this issue now, if you are still seeing the problem on the latest version of the repo please let us know. A new release is hopefully not too far away (more details on the mailing list).
