### ISSUE TITLE
EHOSTDOWN from getsockopt must not cause assertion abort; causes SaltStack crashes

### ISSUE THREAD

**Issue by MarkMartinec** [zeromq/zeromq4-1#164]
With zeromq-4.1.5 from FreeBSD ports, as used by SaltStack.

For some time I have been observing instability of a running salt_minion on several of our FreeBSD hosts: after a couple of days Salt master loses contact with most FreeBSD hosts, but Linux hosts remain connected. After such event one can find a coredump of a salt-minion process (written in python) on such systems, and manually restarting a salt_minion is needed.

After adding some debugging, and capturing stdout and stderr of a non-daemonized salt-minion process, the following is the last reported line:

   Host is down (src/tcp_connecter.cpp:359)

So it seems there was some minor network glitch or outage, and libzmq decided to abort the process with an assertion, which is supposed to exempt all usual network socket -related problems and catch only a potential application problem.

The problem is that the exemption list is missing the EHOSTDOWN error code, which should not be a cause of a process abort.

The essential code snippet is shown here:

 /usr/ports/net/libzmq4/work/zeromq-4.1.5/src/tcp_connecter.cpp :

```
 zmq::fd_t zmq::tcp_connecter_t::connect ()
 {
     //  Async connect has finished. Check whether an error occurred
     int err = 0;
     socklen_t len = sizeof err;

     const int rc = getsockopt (s, SOL_SOCKET, SO_ERROR, (char*) &err, &len);

     //  Assert if the error was caused by 0MQ bug.
     //  Networking problems are OK. No need to assert.
 [...]
     //  Following code should handle both Berkeley-derived socket
     //  implementations and Solaris.
     if (rc == -1)
         err = errno;
     if (err != 0) {
         errno = err;
         errno_assert (
             errno == ECONNREFUSED ||
             errno == ECONNRESET ||
             errno == ETIMEDOUT ||
             errno == EHOSTUNREACH ||
   +         errno == EHOSTDOWN ||
             errno == ENETUNREACH ||
             errno == ENETDOWN ||
             errno == EINVAL);
         return retired_fd;
     }
```

So, please add the missing "errno == EHOSTDOWN ||" exemption to the errno_assert list.

Here is the patch:

```
--- src/tcp_connecter.cpp~      2016-06-17 13:38:14.000000000 +0200
+++ src/tcp_connecter.cpp       2017-02-23 17:38:25.616705000 +0100
@@ -355,4 +355,5 @@
             errno == ETIMEDOUT ||
             errno == EHOSTUNREACH ||
+            errno == EHOSTDOWN ||
             errno == ENETUNREACH ||
             errno == ENETDOWN ||

```

I don't know about the equivalent code section a couple of lines higher, pertaining to Windows. If a Windows system has an errno code WSAEHOSTDOWN known, it should be added there too.

Btw, the equivalent sister patch for the FreeBSD port net/libzmq4 is here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217313

**Comment by bluca** [comment]
Could you please send a pr to the libzmq repository? And then we can backport

**Comment by MarkMartinec** [comment]
> Could you please send a pr to the libzmq repository? And then we can backport

Done: https://github.com/zeromq/libzmq/issues/2351.
Thanks for the attention!

**Comment by MarkMartinec** [comment]
Actually, now that I look at a diff between tcp_connecter.cpp in libzmq/src/ and zeromq4-1/src/ I see they are quite different. In particular, the error handling case (in discussion here) has been inverted, so instead of listing 'good expected' codes the libzmq branch now lists known bad error codes (which makes better sense), so my problem report only affects the zeromq/zeromq4-1 branch and not the libzmq.

I should be closing the zeromq/libzmq#2351 as a non-issue.

So what would be the appropriate action: add the minimalistic patch (adding one line) as suggested above, or bring in the rewritten assert code from zeromq/libzmq, or bring in the entire new tcp_connecter.cpp from zeromq/libzmq ?

**Comment by bluca** [comment]
I would recommend a minimalistic patch given 4.1 is a stable release. Thanks for looking into this, I'll close the other issue.

**Comment by MarkMartinec** [comment]
Running the patched code on our servers now - I want to make sure that no other similar hickup can trigger the assert unnecessarily (I'd say it is in general bad practice for a library to cause a program to abort, with no way for an application to protect itself). Will provide a pull request, I haven't forgotten about it, thanks for the feedback.

**Comment by bluca** [comment]
Thanks for taking this fix forward.

For the assert design decisions, if you are interested please see:
http://zguide.zeromq.org/php:chapter2#toc17
http://grokbase.com/t/zeromq/zeromq-dev/08cf6qpw56/error-handling-assert
https://en.wikipedia.org/wiki/Fail-fast

**Comment by bluca** [comment]
@MarkMartinec any updates on your tests?

**Comment by MarkMartinec** [comment]
Btw, the FreeBSD port has moved to zeromq version 4.2.2 by now, so this is no longer an issue for me. Regarding the Windows code path: a friend of mine confirmed that Windows does have a WSAEHOSTDOWN error code, so the change should be fine for both Unix and Windows.

**Comment by bluca** [comment]
great, thanks!
