### ISSUE TITLE
fix to pubsub inproc issue not backported

### ISSUE THREAD

**Issue by pijyoi** [zeromq/zeromq4-1#165]
Could the following PR made in Nov 2014 please be backported?
issue: https://github.com/zeromq/libzmq/issues/1257
fixed by: https://github.com/zeromq/libzmq/pull/1262

**Comment by bluca** [comment]
sure, could you please send a PR?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zeromq4-1/pull/166
