### ISSUE TITLE
Ubuntu Mate 16.04: zeromq-4.1.2 fails make check

### ISSUE THREAD

**Issue by rjpeek** [zeromq/zeromq4-1#167]
I followed the directions from this link: https://tuananh.org/2015/06/16/how-to-install-zeromq-on-ubuntu/
When I try to install zeromq it fails when I type make check with the following:

rjpeek@rjpeek-G31-M7-TE:~/zeromq-4.1.2$ make check
Making check in doc
make[1]: Entering directory '/home/rjpeek/zeromq-4.1.2/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/rjpeek/zeromq-4.1.2/doc'
make[1]: Entering directory '/home/rjpeek/zeromq-4.1.2'
  CXX      src/libzmq_la-address.lo
  CXX      src/libzmq_la-clock.lo
  CXX      src/libzmq_la-ctx.lo
  CXX      src/libzmq_la-curve_client.lo
src/curve_client.cpp: In constructor ‘zmq::curve_client_t::curve_client_t(const zmq::options_t&)’:
src/curve_client.cpp:61:18: error: ignoring return value of ‘int sodium_init()’, declared with attribute warn_unused_result [-Werror=unused-result]
     sodium_init();
                  ^
cc1plus: all warnings being treated as errors
Makefile:2529: recipe for target 'src/libzmq_la-curve_client.lo' failed
make[1]: *** [src/libzmq_la-curve_client.lo] Error 1
make[1]: Leaving directory '/home/rjpeek/zeromq-4.1.2'
Makefile:3112: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
rjpeek@rjpeek-G31-M7-TE:~/zeromq-4.1.2$ 

I am able to get "make check" to pass and install if I configure with this: ./configure --without-libsodium

**Comment by bluca** [comment]
Those instrunctions from that link are completely wrong.

Just do:

```sudo apt-get install libzmq3-dev```
