### ISSUE TITLE
test_security_null fails for latest (4.1.7)

### ISSUE THREAD

**Issue by xor-gate** [zeromq/zeromq4-1#173]
We are upgrading our custom build debian package but our CI is unable to finalize the build due too:

```
====================================
   zeromq 4.1.7: ./test-suite.log
====================================

# TOTAL: 63
# PASS:  62
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_security_null
========================

lt-test_security_null: tests/test_security_null.cpp:109: int main(): Assertion `rc == 0' failed.
```

We use the latest master, building under Debian 8 with GCC.

**Comment by bluca** [comment]
Feel free to send a PR to fix the issue, but note that there is not much development on 4.1.x. Are you aware that we have APT repositories with the latest releases for most distros, including Debian 8? That will allow you to avoid rebuilding the library:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libzmq3-dev

**Comment by xor-gate** [comment]
Thanks @bluca I will look into it. Also I prefer to use community supported versions. But currently we use 4.1.x in production and don't want to touch it to much.

**Comment by sigiesec** [comment]
Backporting from 4.2/4.3 will not be easy, unfortunately. Maybe it is only a bug in the test rather than the production code.

**Comment by xor-gate** [comment]
Sorry for the noise, our CI platform had running a process on port 9000. So the `rc = zmq_bind (server, "tcp://127.0.0.1:9000");` did fail.

**Comment by sigiesec** [comment]
Ok, thanks for checking. In 4.2 the tests have been improved such that they no longer used fixed port numbers.
