### ISSUE TITLE
Espresso (zmq_proxy) doesn't work anymore

### ISSUE THREAD

**Issue by metadings** [zeromq/zeromq4-1#27]
I'm issuing this because I don't know if I should change this.
There was this change to `zeromq4-1`, which seems to block (the [Espresso example](https://github.com/metadings/zguide/blob/master/examples/C%23/espresso.cs)) until forever:

	@@ -159,14 +159,16 @@ int zmq::proxy (
	         }
	         //  Process a request
	         if (state == active
	-        &&  items [0].revents & ZMQ_POLLIN) {
	+        &&  items [0].revents & ZMQ_POLLIN
	+        &&  items [1].revents & ZMQ_POLLOUT) {
	             rc = forward(frontend_, backend_, capture_,msg);
	             if (unlikely (rc < 0))
	                 return -1;
	         }
	         //  Process a reply
	         if (state == active
	-        &&  items [1].revents & ZMQ_POLLIN) {
	+        &&  items [1].revents & ZMQ_POLLIN
	+        &&  items [0].revents & ZMQ_POLLOUT) {
	             rc = forward(backend_, frontend_, capture_,msg);
	             if (unlikely (rc < 0))
	                 return -1;

Now the question is: Should I remove that `ZMQ_POLLOUT`s again, or should we use `ZMQ_DONTWAIT` (instead of `0`) in the forward function?

Actually I don't even see the `zmq_proxy` registering the `ZMQ_POLLOUT`, there's just `ZMQ_POLLIN`; so does this make sense at all?

    zmq_pollitem_t items [] = {
        { frontend_, 0, ZMQ_POLLIN, 0 },
        { backend_, 0, ZMQ_POLLIN, 0 },
        { control_, 0, ZMQ_POLLIN, 0 }
    };

**Comment by hintjens** [comment]
Hmm. The change did fix a problem (the proxy never exited), however it's
broken the existing API, which is not good. Does your suggested change deal
with that?

**Comment by metadings** [comment]
Well, should I leave just the `ZMQ_POLLIN`, without the `ZMQ_POLLOUT` and instead `forward` using `ZMQ_DONTWAIT`?

**Comment by metadings** [comment]
I believe the Publisher which didn't get a Subscriber didn't send a message, just doing ETERM? :)

**Comment by metadings** [comment]
Let's look at the ZMQ_DONTWAIT... Would this change be correct? (See [here the current one](https://github.com/zeromq/zeromq4-1/blob/1c7b09afaf29ad7e1b767c716f674fb56fc13cd7/src/proxy.cpp).)

	int forward(
	        class zmq::socket_base_t *from_,
	        class zmq::socket_base_t *to_,
	        class zmq::socket_base_t *capture_,
	        zmq::msg_t& msg_)
	{
	    int more;
	    size_t moresz;
	    while (true) {
	        int rc = from_->recv (&msg_, ZMQ_DONTWAIT);
	        if (unlikely (rc < 0))
	            return -1;

	        moresz = sizeof more;
	        rc = from_->getsockopt (ZMQ_RCVMORE, &more, &moresz);
	        if (unlikely (rc < 0))
	            return -1;

	        //  Copy message to capture socket if any
	        rc = capture(capture_, msg_, more);
	        if (unlikely (rc < 0))
	            return -1;

	        rc = to_->send (&msg_, (more? ZMQ_SNDMORE: 0) | ZMQ_DONTWAIT);
	        if (unlikely (rc < 0))
	            return -1;
	        if (more == 0)
	            break;
	    }
	    return 0;
	}

**Comment by metadings** [comment]
> Does your suggested change deal with that?
I don't know, I've no problems, neither with `zmq_ctx_term` nor with `zmq_ctx_shutdown`. Please try the Espresso example, which does both and gracefully dies on shutdown - also without the changes.

**Comment by hintjens** [comment]
I'm not going to be able to look at this today. Would you like to bounce
this issue off zeromq-dev?

**Comment by metadings** [comment]
Well let's see these days...

**Comment by hintjens** [comment]
Closing as stale.
