### ISSUE TITLE
MultiThread REQ/REP module question

### ISSUE THREAD

**Issue by znoodl** [zeromq/zeromq4-1#51]
Hi!
I want to build a RPC by using zmq, DEALER accept message and send msg to multithreads worker to handle. But when I sleep one thread by Poco::Thread::sleep, other threads can not handle messages and client cannot recv response until the sleep thread wakeup. 

Thanks .

**Comment by znoodl** [comment]
Sorry to bother you, my code:
```
  if (thread == 1)
    Poco::Thread::sleep(20000 * 1000);//If sleep here, other threads wokes

    void *receiver = zmq_socket (_context, ZMQ_REP);
    zmq_connect (receiver, "inproc://worksocket");
    while (true) 
    {
        int ret = zmq_recv (receiver, buffer, 10, 0);
        int n = buffer.getnum();
        if (n == 1)
             Poco::Thread::sleep(20000);//If sleep here, other threads cannot response msg
        zmq_send (receiver, buff, sizeof(buff), 0);
    }
```

**Comment by znoodl** [comment]
I tested more and now I know if I sleep thread after `zmq_connect (receiver, "inproc://worksocket");`,other threads does works.

**Comment by hintjens** [comment]
Please discuss on zeromq-dev, thank you.
