### ISSUE TITLE
MPL license?

### ISSUE THREAD

**Issue by pombredanne** [zeromq/zeromq4-1#77]
Hi I reckon per http://zeromq.org/area:licensing that the license would be evolved to MPL 2.0 at some time...
Any idea of when?
Thanks!

**Comment by hintjens** [comment]
We've done that on other projects; for libzmq it requires a major work to contact all authors. Not had time for that yet.

**Comment by pombredanne** [comment]
@hintjens Thank you for this super fast reply!
