### ISSUE TITLE
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:239)

### ISSUE THREAD

**Issue by rikvdh** [zeromq/zeromq4-1#86]
Hi Pieter,

I've ran into an assertion today from src/signaler.cpp
```
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:239)
```

At the point where it threw I close multiple sockets and contexts, so I'm not sure how to reproduce. But if I'm able to isolate it, I'll tell.

But I'm looking at the line from the assert:
https://github.com/zeromq/zeromq4-1/blob/master/src/signaler.cpp#L239
 and at the man-page of poll():
http://linux.die.net/man/2/poll

The man-page states that it can return POLLERR, POLLHUP, or POLLNVAL as well. And on closing sockets and contexts I assume that e.g. POLLHUP can occur. Is assert the right choice here?

Greetings,

Rik

**Comment by hintjens** [comment]
Sounds like the code isn't dealing with POLLHUP properly. If you can
reproduce, and make a patch, that'll be welcome.

**Comment by rikvdh** [comment]
Hm.. I'm reading a bit on POLL events. Also in relation to socketpair (in my case) and in what cases the events could occur.

The POLLNVAL occurs when the fd is invalid, but it this may not happen since its a pair and sockets are not closed while the other is left open. The only thing I can think of here is a racecondition in the usage of signalers destructor (calling delete) where someone is about to poll or already polling.

The POLLHUP is only possible when the socket exited. This could be the case, but calling the destructor while someone is waiting in poll seems like bad behavior.

POLLERR is for some other errors, but from what I understand from reading is that this probably doesn't apply for socketpair.

But, I'm still unable to reproduce the issue. But I can't quite understand how the signaler fits in zmq. I see that it is used in mailbox. But then then it is spreads across the source. I want to reproduce, because a blind fix is as good as no fix. You want to make sure there is actually a problem. I'm seeking for a case how a mailbox.recv can occur where a destructor can be called asynchronously, but I can't seem to think of a way.

But nevertheless an assert is probably wrong in signaler. I think it needs an other return value on POLLHUP/NVAL/ERR instead of calling assert.

**Comment by kikosha** [comment]
I also hit this issue
Also, during context close
```c++
__GI_raise() at raise.c:55 0x7ffff4e49267	
__GI_abort() at abort.c:89 0x7ffff4e4aeca	
zmq::zmq_abort() at err.cpp:84 0x7ffff7287759	
zmq::signaler_t::wait() at signaler.cpp:239 0x7ffff72a04fd	
zmq::mailbox_t::recv() at mailbox.cpp:80 0x7ffff728b3a6	
zmq::ctx_t::terminate() at ctx.cpp:167 0x7ffff727b87c	
zmqpp::context::terminate() at 0x7ffff7051b21	
zmqpp::context::~context() at context.hpp:100 0x469a40	
__gnu_cxx::new_allocator<zmqpp::context>::destroy<zmqpp::context>() at new_allocator.h:124 0x48a3c2	
```

From the debugger:
```c++
zmq::signaler_t::wait() at signaler.cpp:239 0x7ffff72a04fd	

    zmq_assert (pfd.revents & POLLIN);
```
Name : pfd
	Details:{fd = 10, events = 1, revents = 32}

**Comment by rikvdh** [comment]
@kikosha Interesting. Can you share a direction on how to reproduce perhaps or share your code? I'm quite stuck on steps to reproduce.

**Comment by kikosha** [comment]
I can't share the code (its huge and not of my possession :) ) but the overall picture is that I have a context object, stored inside a shared_ptr and used by several  sockets running on different threads. Most of them are inproc. The crash happens during the destruction of the outermost wrapper object, sockets are closed beforehand, by different owning threads. Some sockets seem to close during the destruction of context object (Socket operation on non-socket is thrown when I try to close them). This happens when I rapidly create and destroy the outermost wrapper object in a loop. It takes a few hundreds of create/destroy cycles to reproduce. 
If you have some specific things you'd like me to try/debug I can do that

**Comment by hintjens** [comment]
Can we reproduce this on libzmq master? I'm closing this issue, it does not belong here unless it's a problem specific to the 4-1 stable branch.
